version: "3.9"

services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: imobiliaria-app
    volumes:
      - ./backend:/var/www/html
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_DATABASE: imobiliaria
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    depends_on: [db]

  db:
    image: postgres:16
    container_name: imobiliaria-db
    environment:
      POSTGRES_DB: imobiliaria
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
