version: "3.9"

services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: imobiliaria-app
    volumes:
      - ./backend:/var/www/html
    ports:
      - "8000:8000"
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      DB_PORT: 5432
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_DATABASE: imobiliaria
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    depends_on: [db]

  db:
    image: postgres:16
    container_name: imobiliaria-db
    environment:
      POSTGRES_DB: imobiliaria
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: imobiliaria-frontend
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "5173:5173"
    environment:
      CHOKIDAR_USEPOLLING: 'true'
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]

volumes:
  dbdata:
